---
title: "Data Analytics Journey"
site: distill::distill_website
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
Welcome to the home page for [HuangAnni](https://huanganni.netlify.app/huanganni.html)'s assignments for [ISSS608 Visual Analytics and Applications](https://isss608-ay2021-22april.netlify.app/).

Instructor: Dr. Kam Tin Seong, Associate Professor of Information Systems (Practice)
Lesson: Saturday 12:00pm to 3:15pm

Venue: SCIS Seminar Rm B1-1
Syllabus: [click here](https://isss608-ay2021-22april.netlify.app/syllabus.html)
Upcoming lectures and assignments: [click here](https://isss608-ay2021-22april.netlify.app/lesson.html)

# Table of contents
- Week 1 Distill Blog and R markdown
  - [In-class excercise 1](https://huanganni.netlify.app/ic_ex1.html)
  - [Take-home excercise 1](https://huanganni.netlify.app/th_ex/th_ex1.html)
- Week 2 Tableau
  - [In-class excercise 2](https://public.tableau.com/views/Hands-onexcercise2/Dashboard1?:language=en-GB&:display_count=n&:origin=viz_share_link)
  - [Hand-out 2](https://huanganni.netlify.app/th_ex/hd_2.html)
  - [Take-home excercise 2](https://huanganni.netlify.app/th_ex/th_ex2.html)
- Week 3 DataPrep & TreeMap
  - [Hand-out 3](https://huanganni.netlify.app/th_ex/hd_3.html)
  - [Take-home excercise 3](https://huanganni.netlify.app/th_ex/th_ex3.html)
- Week 4 Building Funnel Plot with R
  - [Hand-out 4](https://huanganni.netlify.app/in_class_ex/in-class-ex-04.html)
- Week 5 Time Series and Event Log
  - [Hand-out 5](https://huanganni.netlify.app/in_class_ex/in-class-ex-05.html)
- Week 6 Geo data
  - [Hand-out 6](https://huanganni.netlify.app/in_class_ex/in-class-ex6.html)
  - [Take-home 4](https://huanganni.netlify.app/th_ex/th_ex4.html)
  - [Take-home 5](https://huanganni.netlify.app/th_ex/th_ex5.html)
- Week 6 Social Network
  - [Hand-out 7](https://huanganni.netlify.app/in_class_ex/in-class-ex07.html)
  - [Take-home 6](https://huanganni.netlify.app/th_ex/th_ex6.html)
  - [Cycle-and-checkInNum on tableau](https://public.tableau.com/app/profile/huang.anni/viz/Time-seriesmapwithcycleandcheckInNum/Dashboard1?publish=yes)
- Week 8 Dashboard design
  - [In-class 8 Sparkline and bullet chart](https://huanganni.netlify.app/in_class_ex/in-class-ex-08.html)