---
title: "Take Home Exercise 4"
author:
- name: "Huang Anni"
  affiliation: "Singapore Management University"
description: |
  VAST Challenge 3
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r}
packages = c('ggiraph', 'plotly', 'tidyverse', 'DT','gganimate',
             'knitr', 'ggdist', 'scales', 'grid', 'gridExtra',
             'patchwork','ggsignif','gghighlight',"hrbrthemes",
             'readxl', 'gifski', 'gapminder','treemap', 'treemapify',
             'rPackedBar','ggridges','rmarkdown','crosstalk',
             'd3scatter','tidycensus','timetk','ggseas','lubridate',
             'ggrepel','doSNOW','data.table','ViSiElse','plyr')

for(p in packages) {
  if(!require(p, character.only = T)) {
    install.packages(p)
  }
  library(p, character.only = T)
}
```

## Read in all the activity logs

```{r read-in-data, eval=FALSE}
csv.list <- list.files(path="./rawdata/Activity Logs", pattern=".csv$", full.names=TRUE)

cl <- makeCluster(4)
registerDoSNOW(cl)

pb <- txtProgressBar(max=length(csv.list), style=3)
pbu <- function(i) setTxtProgressBar(pb, i)
dt <- setDT(ldply(csv.list, fread, .parallel=TRUE, .paropts=list(.options.snow=list(progress=pbu))))

stopCluster(cl)
```

## Save the data for two participants

```{r save-filtered-data, eval=FALSE}
glimpse(dt)
participantId_list <- c(79, 80)
two_par_log <- dt %>%
  filter(participantId %in% participantId_list)
write_csv(two_par_log, "./data/two_participants_log.csv")

## Read in the filtered data
```

```{r first-draft}
two_par_log <- read_csv("./data/two_participants_log.csv")
paged_table(two_par_log)
```

```{r}
two_par_log$end_timestamp <- two_par_log$timestamp + lubridate::minutes(5)
time_line <- two_par_log %>%
  filter( date(two_par_log$timestamp) == '2022-03-01' ) #& participantId == 79

p1<-ggplot()+
  geom_segment(data=time_line,mapping=aes(x=timestamp,
                                          xend=end_timestamp,
                                          y=currentMode, 
                                          yend = currentMode, 
                                          color= currentMode),
               size=6)+
  facet_grid(participantId~.) +
  theme(legend.position = 'top',
        legend.title=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size=10)) +
  labs(title="Fig1. Daily Routines of Two Selected Participant(79 vs 80)",
       subtitle="79 goes to home after work while 80 has some recreation after work")

p1

```

```{r}
two_par_log$end_timestamp <- two_par_log$timestamp + lubridate::minutes(5)
time_line <- two_par_log %>%
  filter( date(two_par_log$timestamp) == '2022-03-01' ) #& participantId == 79
  # filter( date(two_par_log$timestamp) == '2022-03-01' ) #& participantId == 79
p2 <- ggplot()+
  geom_segment(data=time_line,mapping=aes(x=timestamp,
                                          xend=end_timestamp,
                                          y=hungerStatus, 
                                          yend = hungerStatus, 
                                          color= hungerStatus),
               size=6)+
  facet_grid(.~participantId~.) +
  theme(legend.position = 'top',
        legend.title=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size=10)) +
  labs(title="Fig2. Hunger Status of Two Selected Participant(79 vs 80)",
       subtitle="79 only eat 3 times a day but become staving after 18:00 while 80 eat 4 times a day and do not feel starving at all")

p2
```

```{r}
wkday_levels <- c('Saturday', 'Friday', 
                  'Thursday', 'Wednesday', 
                  'Tuesday', 'Monday', 
                  'Sunday')
make_hr_wkday <- function(ts, sleepStatus) {
  real_times <- ymd_hms(ts, quiet = TRUE)
  dt <- data.table(wkday = weekdays(real_times),
                   hour = hour(real_times))
  return(dt)
}

sleep_hours <- two_par_log %>%
  group_by(weekdays(timestamp),sleepStatus) %>%
  count(timestamp)
sleep_hours
sleep_hour_by_part <- count(
  sleepStatus, participantId) %>%
  mutate(percent = percent(n/sum(n))) %>%
  arrange(desc(n))
```